#############################################################################
# Makefile for building: matrix_browser
# Generated by qmake (2.01a) (Qt 4.7.2) on: Fri Oct 21 08:17:05 2011
# Project:  matrix_browser.pro
# Template: app
# Command: /home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/bin/qmake -o Makefile matrix_browser.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT)/QtGui -I$(OE_QMAKE_INCDIR_QT)/QtWebKit -I$(OE_QMAKE_INCDIR_QT) -I. -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,$(OE_QMAKE_LIBDIR_QT)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -lQtWebKitE -lQtGuiE -lQtNetworkE -lQtCoreE -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp moc_test.cpp
OBJECTS       = main.o \
		moc_test.o
DIST          = ../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		matrix_browser.pro
QMAKE_TARGET  = matrix_browser
DESTDIR       = 
TARGET        = matrix_browser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: matrix_browser.pro  ../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf ../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtWebKitE.prl \
		/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtGuiE.prl \
		/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtNetworkE.prl \
		/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtCoreE.prl
	$(QMAKE) -o Makefile matrix_browser.pro
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++.conf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
../../linux-devkit/arm-arago-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtWebKitE.prl:
/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtGuiE.prl:
/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtNetworkE.prl:
/home/franklin/ti-sdk-am37x-evm-05.03.00.00/linux-devkit/arm-arago-linux-gnueabi/usr/lib/libQtCoreE.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile matrix_browser.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/matrix_browser1.0.0 || $(MKDIR) .tmp/matrix_browser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/matrix_browser1.0.0/ && $(COPY_FILE) --parents test.h .tmp/matrix_browser1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/matrix_browser1.0.0/ && (cd `dirname .tmp/matrix_browser1.0.0` && $(TAR) matrix_browser1.0.0.tar matrix_browser1.0.0 && $(COMPRESS) matrix_browser1.0.0.tar) && $(MOVE) `dirname .tmp/matrix_browser1.0.0`/matrix_browser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/matrix_browser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_test.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_test.cpp
moc_test.cpp: test.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) test.h -o moc_test.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_test.o: moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test.o moc_test.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/./ || $(MKDIR) $(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/./ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/franklin/ti-sdk-am37x-evm-05.03.00.00/example-applications/matrix_browser/./ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

